version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5

  rag-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER:-local}
      - LOCAL_MODEL_NAME=${LOCAL_MODEL_NAME:-all-MiniLM-L6-v2}
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8080
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama:11434}
    depends_on:
      chromadb:
        condition: service_healthy
    volumes:
      - model_cache:/root/.cache/huggingface
    restart: unless-stopped

  # Optional: Ollama service for local LLM embeddings
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    profiles:
      - ollama
    restart: unless-stopped

volumes:
  chromadb_data:
    driver: local
  model_cache:
    driver: local
  ollama_data:
    driver: local
